version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t kamblesuraj432/your_image_name:$CIRCLE_SHA1 .
      - run:
          name: Login to DockerHub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Push Docker Image to DockerHub
          command: |
            docker push kamblesuraj432/your_image_name:$CIRCLE_SHA1

  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate && pytest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - test:
          requires:
            - build

