version: 2.1
jobs:
  build:
    machine: true
    resource_class: kamblrsuraj432/testclass
    steps:
      - run: echo $USER && whoami
  test:
    machine: true
    resource_class: kamblrsuraj432/testclass
    steps:
      - run: cd /home/ubuntu && mkdir suraj

workflows:
    testing:
       jobs:
        - build
        - test
