version: 2.1

jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker:
      - run:
          name: Build Docker Image
          command: |
            docker build -t kamblesuraj432/your_image_name:$CIRCLE_SHA1 .
      - run:
          name: Login to DockerHub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Push Docker Image to DockerHub
          command: |
            docker push kamblesuraj432/your_image_name:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build

